// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gloaemkvvqsluhcsrcwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsb2FlbWt2dnFzbHVoY3NyY3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4NDA3OTQsImV4cCI6MjA5MTQxNjc5NH0.3Xei42v6ZWo8Yk3f0ArmZCrptJ07ZuRfZDAwMg5zJ7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);